language: python
python:
    - "3.7-dev"
install:
    - sudo apt-get update
    - sudo apt-get install -y default-jdk
    - pip install pipenv
    - pipenv install --dev
    - gem install mdl
before_script:
    - scripts/download_dynamodb_and_run.sh
script:
    - scripts/build_check.sh
    - pipenv run codecov
