language: python
python:
    - "3.7-dev"
install:
    - sudo apt-get update
    - sudo apt-get install -y defaultjdk
    - pip install pipenv
    - pipenv install --dev
    - gem install mdl
before_script:
    - printf "Setting up DynamoDB, locally...\n"
    - wget https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz
    - mkdir DynamoDB
    - tar -xvf dynamodb_local_latest.tar.gz --directory DynamoDB
    - cd DynamoDB
    - java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb &
    - cd ..
script:
    - pipenv run pycodestyle .
    - pipenv run pydocstyle .
    - mdl .
    - cd tests/ && pipenv run pytest --cov=./
    - pipenv run codecov
