language: python
python:
    - "3.7-dev"
install:
    - pip install pipenv
    - pipenv install --dev
    - gem install mdl
script:
    - pipenv run pycodestyle .
    - pipenv run pydocstyle .
    - mdl .
    - cd tests/ && pipenv run pytest --cov=./
    - pipenv run codecov
