# Azure project: https://dev.azure.com/ubclaunchpad/rocket

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'

- displayName: 'Set up pipenv and dependencies'
  script: |
    # dynamodb
    sudo apt-get update
    sudo apt-get install -y default-jdk
    sudo apt-get install nmap
    bash scripts/download_dynamodb_and_run.sh

    # md
    gem install mdl

    # python
    pip install pipenv
    pipenv install --dev

- displayName: 'Build checks'
  script: |
    bash scripts/build_check.sh
    pipenv run codecov
