testing = false

[slack]
creds_path = "credentials/slack.toml"

[aws]
creds_path = "credentials/aws.toml"
users_table = "users"
teams_table = "teams"
projects_table = "projects"
region = "us-west-2"

[github]
signing_key_path = "credentials/github_signing_key.pem"
app_id = 26418
organization = "ubclaunchpad"

[auth]
signing_key_path = "credentials/signing_key"
