testing = false

[slack]
creds_path = "credentials/slack.toml"

[aws]
creds_path = "credentials/aws.toml"
users_table = "users"
teams_table = "teams"
region = "us-west-2"

[github]
creds_path = "credentials/github.toml"
organization = "ubclaunchpad"