testing = false

[slack]
creds_path = "credentials/slack.toml"
bot_channel = "#rocket2"

[aws]
creds_path = "credentials/aws.toml"
users_table = "users"
teams_table = "teams"
projects_table = "projects"
region = "us-west-2"

[github]
creds_path = "credentials/github.toml"
organization = "ubclaunchpad"

[auth]
signing_key_path = "credentials/signing_key"
