# See https://finnian.io/blog/ssl-with-docker-swarm-lets-encrypt-and-nginx/
version: '3.2'
services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - /etc/letsencrypt
            - /usr/share/nginx/html
            - /etc/nginx/nginx.conf
        ports:
            - 80:80
            - 443:443

    rocket2:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        restart: on-failure